spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: q1w2e3r4
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017,localhost:27018,localhost:27019/mailbox?replicaSet=rs0
mybatis:
  type-handlers-package: com.lil.mailbox.lilMailboxServer.datasource.postgres.typehandlers

