spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: user
    password: q1w2e3r4
    driver-class-name: org.postgresql.Driver
mybatis:
  type-handlers-package: com.lil.mailbox.lilMailboxServer.datasource.postgres.typehandlers
