spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER-CLASS-NAME:org.postgresql.Driver}
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/lil-mailbox-db}
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port:  ${SPRING_REDIS_PORT:6379}
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  cache:
    type: redis
    redis:
      time-to-live: 43200000
  sql:
    init:
      mode: always
mybatis:
  type-handlers-package: com.lil.mailbox.lilMailboxServer.datasource.postgres.typehandlers
server:
  port: 8083
